const products = [
  {
    id: 1,
    name: 'SUP SURFTECH GENERATOR',
    category: 'sap',
    img: '/images/products/SUP SURFTECH GENERATOR.jpg',
    price: 720,
    countInStock: 1,
    rating: 4.5,
    numberOfReviews: 18,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nisl arcu, iaculis at sem et, vulputate consectetur magna. Integer nec nisi eu est semper aliquet at vel lectus. Proin malesuada turpis vel varius mollis. Ut hendrerit neque at turpis accumsan iaculis. Cras in ligula non dolor accumsan malesuada.',
  },
  {
    id: 2,
    name: 'SUP SURFTECH THE LIDO',
    category: 'sap',
    img: '/images/products/SUP SURFTECH THE LIDO.jpg',
    price: 2000,
    countInStock: 2,
    rating: 5,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 3,
    name: 'SURFTECH DREAMLINER SURFBOARD',
    category: 'sap',
    img: '/images/products/SURFTECH DREAMLINER SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 16,
    description: 'lorem ipsum',
  },
  {
    id: 4,
    name: 'SURFTECH X PURA VIDA TCP 2-PIECE ADJUSTABLE PADDLE',
    category: 'sap',
    img: '/images/products/SURFTECH X PURA VIDA TCP 2-PIECE ADJUSTABLE PADDLE.jpg',
    price: 720,
    countInStock: 2,
    rating: 3.5,
    numberOfReviews: 38,
    description: 'lorem ipsum',
  },
  {
    id: 5,
    name: 'FORRO AERO RACK PADS 28 ROOF PADS',
    category: 'sap',
    img: '/images/products/FORRO AERO RACK PADS 28 ROOF PADS.jpg',
    price: 1200,
    countInStock: 2,
    rating: 0.5,
    numberOfReviews: 10,
    description: 'lorem ipsum',
  },
  {
    id: 6,
    name: 'SEAGLASS 2-PIECE ADJUSTABLE PADDLE',
    category: 'sap',
    img: '/images/products/SEAGLASS 2-PIECE ADJUSTABLE PADDLE.jpg',
    price: 720,
    countInStock: 2,
    rating: 5,
    numberOfReviews: 20,
    description: 'lorem ipsum',
  },
  {
    id: 7,
    name: 'SWIFFER-FISH 2-PIECE ADJUSTABLE PADDLE',
    category: 'sap',
    img: '/images/products/SWIFFER-FISH 2-PIECE ADJUSTABLE PADDLE.jpg',
    price: 720,
    countInStock: 2,
    rating: 3,
    numberOfReviews: 50,
    description: 'lorem ipsum',
  },
  {
    id: 8,
    name: 'SUP NSP O2 ALLROUNDER LT',
    category: 'sap',
    img: '/images/products/TABLA DE SUP NSP O2 ALLROUNDER LT.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 9,
    name: 'SUP FANATIC FLY AIR',
    category: 'sap',
    img: '/images/products/SUP FANATIC FLY AIR.jpg',
    price: 1200,
    countInStock: 2,
    rating: 0.5,
    numberOfReviews: 10,
    description: 'lorem ipsum',
  },
  {
    id: 10,
    name: 'ROXY ALUMINIUM PADDLE 3 PIECES PADDLE',
    category: 'sap',
    img: '/images/products/ROXY ALUMINIUM PADDLE 3 PIECES PADDLE.jpg',
    price: 2000,
    countInStock: 2,
    rating: 5,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 11,
    name: 'SKATE MILLER CORPORATE',
    category: 'skate',
    img: '/images/products/SKATE MILLER CORPORATE.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 16,
    description: 'lorem ipsum',
  },
  {
    id: 12,
    name: 'BLACK RACER SPECIAL EDITION',
    category: 'skate',
    img: '/images/products/BLACK RACER SPECIAL EDITION.jpg',
    price: 720,
    countInStock: 2,
    rating: 3.5,
    numberOfReviews: 38,
    description: 'lorem ipsum',
  },
  {
    id: 13,
    name: 'SKATE PLAN B SHECKLER EMBROIDERED',
    category: 'skate',
    img: '/images/products/SKATE PLAN B SHECKLER EMBROIDERED.jpg',
    price: 720,
    countInStock: 2,
    rating: 3,
    numberOfReviews: 50,
    description: 'lorem ipsum',
  },
  {
    id: 14,
    name: 'SURFSKATE SANTA CRUZ WAVE DOT CUT BACK',
    category: 'skate',
    img: '/images/products/SURFSKATE SANTA CRUZ WAVE DOT CUT BACK.jpg',
    price: 720,
    countInStock: 2,
    rating: 5,
    numberOfReviews: 20,
    description: 'lorem ipsum',
  },
  {
    id: 15,
    name: 'SURFSKATE SANTA CRUZ FLAME DOT SHARK',
    category: 'skate',
    img: '/images/products/SURFSKATE SANTA CRUZ FLAME DOT SHARK.jpg',
    price: 720,
    countInStock: 2,
    rating: 4.5,
    numberOfReviews: 18,
    description: 'lorem ipsum',
  },
  {
    id: 16,
    name: 'CREATURES GRIFFIN COLAPINTO LITE PAD',
    category: 'surf',
    img: '/images/products/CREATURES GRIFFIN COLAPINTO LITE PAD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 17,
    name: 'ODYSEA SKIPPER QUADSURFBOARD',
    category: 'surf',
    img: '/images/products/ODYSEA SKIPPER QUADSURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 18,
    name: 'SURF ODYSEA SKIPPER- QUAD 6 SURFBOARD',
    category: 'surf',
    img: '/images/products/SURF ODYSEA SKIPPER- QUAD 6 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 19,
    name: 'TOWN & COUNTRY TANAKA GLIDE 6 8 SURFBOARD',
    category: 'surf',
    img: '/images/products/TOWN & COUNTRY TANAKA GLIDE 6 8 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 20,
    name: 'QUIKSILVER QS SHORT 5 9 BAG',
    category: 'surf',
    img: '/images/products/QUIKSILVER QS SHORT 5 9 BAG.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 21,
    name: 'QUIKSILVER UNION 6 LEASH',
    category: 'surf',
    img: '/images/products/QUIKSILVER UNION 6 LEASH.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 22,
    name: 'FUTURES VII FEA BLACKSTIX 3.0 M TRI-FINS FINS',
    category: 'surf',
    img: '/images/products/FUTURES VII FEA BLACKSTIX 3.0 M TRI-FINS FINS.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 23,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 24,
    name: 'OCEAN EARTH HAPPY HOUR 6 6 - SKY SURFBOARD',
    category: 'surf',
    img: '/images/products/OCEAN EARTH HAPPY HOUR 6 6 - SKY SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 25,
    name: 'INDIO ENDURANCE PLUS 5 10 SURFBOARD',
    category: 'surf',
    img: '/images/products/INDIO ENDURANCE PLUS 5 10 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 26,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 27,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 28,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 29,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 30,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 31,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 32,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 33,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 34,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
  {
    id: 35,
    name: 'VENON GOPHER 7 0 SURFBOARD',
    category: 'surf',
    img: '/images/products/VENON GOPHER 7 0 SURFBOARD.jpg',
    price: 720,
    countInStock: 2,
    rating: 4,
    numberOfReviews: 12,
    description: 'lorem ipsum',
  },
];

export default products;
